version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    commands:
      - echo installation start
      - git config --global credential.UseHttpPath true
  pre_build:
    commands:
      - echo prebuild start
      - git clone https://github.com/abby-1992/poc-test.git
      - git clone https://github.com/Spak-Digital-GmbH/commonUtils.git
      - echo pre build step done
  build:
    commands:
      - echo build start
      - ls
      - cd poc-test
      - ls
      - cat countFile.txt
      - echo build step done
  post_build:
    commands:
      - echo post build start
      - echo post build completed